// Cele mai frecvente cuvinte englezești (A1–A2).
// Vocabularul din banca elevului nu va include aceste cuvinte.

const COMMON_WORDS = new Set([
  // Articles / determiners
  'a','an','the','this','that','these','those',
  // Pronouns
  'i','me','my','mine','myself','you','your','yours','yourself',
  'he','him','his','himself','she','her','hers','herself',
  'it','its','itself','we','us','our','ours','ourselves',
  'they','them','their','theirs','themselves',
  'who','whom','whose','what','which','whoever','whatever',
  // Conjunctions & prepositions
  'and','or','but','nor','so','yet','for','if','as','that',
  'because','since','although','though','while','until','unless',
  'whether','when','where','after','before','than','both','either',
  'in','on','at','by','to','from','of','off','up','down','out',
  'over','under','into','onto','upon','with','without','about',
  'above','below','between','among','through','during','along',
  'against','around','beside','behind','beyond','near','inside',
  'outside','across','within','throughout','toward','towards',
  // Modal & auxiliary verbs
  'be','am','is','are','was','were','been','being',
  'have','has','had','having',
  'do','does','did','done','doing',
  'will','would','could','should','may','might','can','shall','must','ought',
  // High-frequency verbs
  'go','went','gone','going',
  'get','got','gotten','getting',
  'come','came','coming',
  'make','made','making',
  'take','took','taken','taking',
  'say','said','saying',
  'know','knew','known','knowing',
  'think','thought','thinking',
  'see','saw','seen','seeing',
  'look','looked','looking',
  'want','wanted','wanting',
  'give','gave','given','giving',
  'use','used','using',
  'find','found','finding',
  'tell','told','telling',
  'ask','asked','asking',
  'feel','felt','feeling',
  'try','tried','trying',
  'call','called','calling',
  'keep','kept','keeping',
  'let','letting',
  'put','putting',
  'run','ran','running',
  'seem','seemed','seeming',
  'show','showed','shown','showing',
  'hear','heard','hearing',
  'play','played','playing',
  'move','moved','moving',
  'live','lived','living',
  'help','helped','helping',
  'turn','turned','turning',
  'start','started','starting',
  'need','needed','needing',
  'leave','left','leaving',
  'read','reading',
  'sit','sat','sitting',
  'stand','stood','standing',
  'bring','brought','bringing',
  'begin','began','begun','beginning',
  'hold','held','holding',
  'walk','walked','walking',
  'write','wrote','written','writing',
  'buy','bought','buying',
  'eat','ate','eaten','eating',
  'send','sent','sending',
  'meet','met','meeting',
  'set','setting',
  'wait','waited','waiting',
  'pay','paid','paying',
  'open','opened','opening',
  'close','closed','closing',
  'follow','followed','following',
  'stop','stopped','stopping',
  'watch','watched','watching',
  'stay','stayed','staying',
  'fall','fell','fallen','falling',
  'cut','cutting',
  'spend','spent','spending',
  'grow','grew','grown','growing',
  'talk','talked','talking',
  'win','won','winning',
  'lose','lost','losing',
  'love','loved','loving',
  'like','liked','liking',
  'care','cared','caring',
  'add','added','adding',
  'die','died','dying',
  'become','became','becoming',
  'learn','learned','learning',
  'change','changed','changing',
  'lead','led','leading',
  'understand','understood','understanding',
  'happen','happened','happening',
  'allow','allowed','allowing',
  'include','included','including',
  'continue','continued','continuing',
  'create','created','creating',
  'appear','appeared','appearing',
  'build','built','building',
  'reach','reached','reaching',
  'remember','remembered','remembering',
  'speak','spoke','spoken','speaking',
  'return','returned','returning',
  'end','ended','ending',
  'work','worked','working',
  // Basic adjectives
  'good','great','bad','big','small','little','large','long','short',
  'new','old','young','high','low','hot','cold','hard','easy',
  'fast','slow','full','empty','clean','dirty','same','different',
  'first','last','next','main','real','true','false','right','wrong',
  'free','open','dark','light','sure','ready','able','own',
  'happy','sad','nice','kind','funny','silly','pretty','beautiful',
  'strong','weak','rich','poor','safe','late','early','whole',
  'white','black','red','blue','green','yellow','brown','grey','gray','orange','purple','pink',
  // Basic nouns
  'time','day','year','week','month','hour','minute','second',
  'man','woman','boy','girl','child','baby','person','people','family',
  'friend','mother','father','parent','son','daughter','brother','sister',
  'home','house','room','door','window','floor','wall',
  'water','food','air','fire','earth','sky','sun','moon','rain','snow',
  'car','road','street','city','town','country','world',
  'school','class','teacher','student','book','page','word','name',
  'money','job','work','company','office','team','group',
  'hand','head','eye','ear','nose','mouth','face','body','heart',
  'number','part','place','point','line','side','end','way','case',
  'fact','idea','life','thing','lot','kind','type','form','set',
  'day','night','morning','evening','afternoon','today','tomorrow','yesterday',
  'game','team','music','film','movie','show','phone','computer',
  'problem','question','answer','result','reason','moment','information','news',
  // Basic adverbs
  'very','just','not','now','still','also','too','really','quite',
  'here','there','when','where','why','how','again','always','never',
  'sometimes','often','usually','already','soon','only','even','else',
  'maybe','perhaps','almost','enough','ever','back','away','once',
  'together','around','today','more','less','most','least','simply',
  'actually','finally','however','therefore','although','especially',
  'already','again','well','else','far','early','late','near',
]);

/**
 * Returnează true dacă cuvântul este prea frecvent pentru banca de vocabular.
 * Ignoră majusculele, spațiile și cratimele (cuvintele compuse trec filtrul).
 */
export function isCommonWord(word: string): boolean {
  // Cuvintele compuse cu cratimă (ex. "well-being") nu sunt filtrate
  if (word.includes('-')) return false;
  return COMMON_WORDS.has(word.toLowerCase().trim());
}

export function filterUncommonWords<T extends { en: string }>(words: T[]): T[] {
  return words.filter(w => !isCommonWord(w.en));
}
